/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as KegiatanRouteImport } from './routes/kegiatan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as SdRouteImport } from './routes/sd'
import { Route as SmpRouteImport } from './routes/smp'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as BeritaIndexRouteImport } from './routes/berita/index'
import { Route as BeritaSlugRouteImport } from './routes/berita/$slug'
import { Route as PpdbIndexRouteImport } from './routes/ppdb/index'
import { Route as PpdbSdRouteImport } from './routes/ppdb/sd'
import { Route as PpdbSmpRouteImport } from './routes/ppdb/smp'
import { Route as PpdbStatusRouteImport } from './routes/ppdb/status'
import { Route as AdminPpdbIndexRouteImport } from './routes/admin/ppdb/index'
import { Route as AdminPpdbIdRouteImport } from './routes/admin/ppdb/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const KegiatanRoute = KegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const SdRoute = SdRouteImport.update({
  id: '/sd',
  path: '/sd',
  getParentRoute: () => rootRouteImport,
} as any)
const SmpRoute = SmpRouteImport.update({
  id: '/smp',
  path: '/smp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbIndexRoute = PpdbIndexRouteImport.update({
  id: '/ppdb/',
  path: '/ppdb/',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbSdRoute = PpdbSdRouteImport.update({
  id: '/ppdb/sd',
  path: '/ppdb/sd',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbSmpRoute = PpdbSmpRouteImport.update({
  id: '/ppdb/smp',
  path: '/ppdb/smp',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbStatusRoute = PpdbStatusRouteImport.update({
  id: '/ppdb/status',
  path: '/ppdb/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPpdbIndexRoute = AdminPpdbIndexRouteImport.update({
  id: '/admin/ppdb/',
  path: '/admin/ppdb/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPpdbIdRoute = AdminPpdbIdRouteImport.update({
  id: '/admin/ppdb/$id',
  path: '/admin/ppdb/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/galeri': typeof GaleriRoute
  '/kegiatan': typeof KegiatanRoute
  '/kontak': typeof KontakRoute
  '/sd': typeof SdRoute
  '/smp': typeof SmpRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/ppdb/sd': typeof PpdbSdRoute
  '/ppdb/smp': typeof PpdbSmpRoute
  '/ppdb/status': typeof PpdbStatusRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/ppdb/': typeof PpdbIndexRoute
  '/admin/ppdb/$id': typeof AdminPpdbIdRoute
  '/admin/ppdb/': typeof AdminPpdbIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/galeri': typeof GaleriRoute
  '/kegiatan': typeof KegiatanRoute
  '/kontak': typeof KontakRoute
  '/sd': typeof SdRoute
  '/smp': typeof SmpRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/ppdb/sd': typeof PpdbSdRoute
  '/ppdb/smp': typeof PpdbSmpRoute
  '/ppdb/status': typeof PpdbStatusRoute
  '/admin': typeof AdminIndexRoute
  '/berita': typeof BeritaIndexRoute
  '/ppdb': typeof PpdbIndexRoute
  '/admin/ppdb/$id': typeof AdminPpdbIdRoute
  '/admin/ppdb': typeof AdminPpdbIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/galeri': typeof GaleriRoute
  '/kegiatan': typeof KegiatanRoute
  '/kontak': typeof KontakRoute
  '/sd': typeof SdRoute
  '/smp': typeof SmpRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/ppdb/sd': typeof PpdbSdRoute
  '/ppdb/smp': typeof PpdbSmpRoute
  '/ppdb/status': typeof PpdbStatusRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/ppdb/': typeof PpdbIndexRoute
  '/admin/ppdb/$id': typeof AdminPpdbIdRoute
  '/admin/ppdb/': typeof AdminPpdbIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/galeri'
    | '/kegiatan'
    | '/kontak'
    | '/sd'
    | '/smp'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/news'
    | '/berita/$slug'
    | '/ppdb/sd'
    | '/ppdb/smp'
    | '/ppdb/status'
    | '/admin/'
    | '/berita/'
    | '/ppdb/'
    | '/admin/ppdb/$id'
    | '/admin/ppdb/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/galeri'
    | '/kegiatan'
    | '/kontak'
    | '/sd'
    | '/smp'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/news'
    | '/berita/$slug'
    | '/ppdb/sd'
    | '/ppdb/smp'
    | '/ppdb/status'
    | '/admin'
    | '/berita'
    | '/ppdb'
    | '/admin/ppdb/$id'
    | '/admin/ppdb'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/galeri'
    | '/kegiatan'
    | '/kontak'
    | '/sd'
    | '/smp'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/news'
    | '/berita/$slug'
    | '/ppdb/sd'
    | '/ppdb/smp'
    | '/ppdb/status'
    | '/admin/'
    | '/berita/'
    | '/ppdb/'
    | '/admin/ppdb/$id'
    | '/admin/ppdb/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GaleriRoute: typeof GaleriRoute
  KegiatanRoute: typeof KegiatanRoute
  KontakRoute: typeof KontakRoute
  SdRoute: typeof SdRoute
  SmpRoute: typeof SmpRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsRoute: typeof AdminNewsRoute
  BeritaSlugRoute: typeof BeritaSlugRoute
  PpdbSdRoute: typeof PpdbSdRoute
  PpdbSmpRoute: typeof PpdbSmpRoute
  PpdbStatusRoute: typeof PpdbStatusRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  PpdbIndexRoute: typeof PpdbIndexRoute
  AdminPpdbIdRoute: typeof AdminPpdbIdRoute
  AdminPpdbIndexRoute: typeof AdminPpdbIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kegiatan': {
      id: '/kegiatan'
      path: '/kegiatan'
      fullPath: '/kegiatan'
      preLoaderRoute: typeof KegiatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sd': {
      id: '/sd'
      path: '/sd'
      fullPath: '/sd'
      preLoaderRoute: typeof SdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smp': {
      id: '/smp'
      path: '/smp'
      fullPath: '/smp'
      preLoaderRoute: typeof SmpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb/': {
      id: '/ppdb/'
      path: '/ppdb'
      fullPath: '/ppdb/'
      preLoaderRoute: typeof PpdbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb/sd': {
      id: '/ppdb/sd'
      path: '/ppdb/sd'
      fullPath: '/ppdb/sd'
      preLoaderRoute: typeof PpdbSdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb/smp': {
      id: '/ppdb/smp'
      path: '/ppdb/smp'
      fullPath: '/ppdb/smp'
      preLoaderRoute: typeof PpdbSmpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb/status': {
      id: '/ppdb/status'
      path: '/ppdb/status'
      fullPath: '/ppdb/status'
      preLoaderRoute: typeof PpdbStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ppdb/': {
      id: '/admin/ppdb/'
      path: '/admin/ppdb'
      fullPath: '/admin/ppdb/'
      preLoaderRoute: typeof AdminPpdbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ppdb/$id': {
      id: '/admin/ppdb/$id'
      path: '/admin/ppdb/$id'
      fullPath: '/admin/ppdb/$id'
      preLoaderRoute: typeof AdminPpdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GaleriRoute: GaleriRoute,
  KegiatanRoute: KegiatanRoute,
  KontakRoute: KontakRoute,
  SdRoute: SdRoute,
  SmpRoute: SmpRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsRoute: AdminNewsRoute,
  BeritaSlugRoute: BeritaSlugRoute,
  PpdbSdRoute: PpdbSdRoute,
  PpdbSmpRoute: PpdbSmpRoute,
  PpdbStatusRoute: PpdbStatusRoute,
  AdminIndexRoute: AdminIndexRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  PpdbIndexRoute: PpdbIndexRoute,
  AdminPpdbIdRoute: AdminPpdbIdRoute,
  AdminPpdbIndexRoute: AdminPpdbIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
